site_name: Eric
site_url: http://theguodong.com

nav:
  - é¦–é¡µ: 
    - æ•°æ®åº“:
      - MySQL:
        - MySQLå†…ç½®å‡½æ•°: ./articles/DataBase/MySQL/MySQLå†…ç½®å‡½æ•°.md
        - MySQLå­˜å‚¨è¿‡ç¨‹: ./articles/DataBase/MySQL/MySQLå­˜å‚¨è¿‡ç¨‹.md
  - ç›¸å†Œ: 
    - gallery.md
    - æ—¶é—´çº¿:
      - 2024: 
        - GR3ï½œéº»æœ¨ä¸ä»çš„æ—¥å­é‡Œï¼Œè®°å½•å°±æ˜¯åæŠ—: ./gallery/2024-05-19/gallery.md
        - æ˜¥æ„æš–æš–ï¼Œå²æœˆç¼“ç¼“ï¼Œåœ¨æ„Ÿå—ï¼Œåœ¨è®°å½•ï¼Œåœ¨çæƒœ: ./gallery/2024-04-05/gallery.md
        - ä¸€èµ·å»å©ºæºå§ï¼Œçœ‹é‚£åº§å±±å´–ä¸Šè‚†æ„ç”Ÿé•¿çš„æ‘è½: ./gallery/2024-03-23/gallery.md
        - ä¹Œé•‡ï½œå¤©é’è‰²ç­‰çƒŸé›¨ï¼Œè€Œæˆ‘åœ¨ç­‰ä½ : ./gallery/2024-03-08/gallery.md
      - 2023:
        - æ€»è¦å¸¦ç€å–œæ¬¢çš„äººï¼Œå»çœ‹ä¸€çœ¼è”šè“çš„èµ›é‡Œæœ¨æ¹–: ./gallery/2023-06-09/gallery.md
        - ä½ ä¸åœ¨é‡åº†çš„æ—¥å­ï¼Œæˆ‘æ›¿ä½ å¹äº†å˜‰é™µæ±Ÿçš„æ™šé£: ./gallery/2023-06-08/gallery.md
        - åœ¨å……æ»¡é˜³å…‰çš„åœ°æ–¹ï¼Œå®‰é™çš„è¿æ¥æ¸©æš–çš„ä¸€å¤©: ./gallery/2023-05-07/gallery.md
        - é’æµ·è´µå¾·ï½œå¥‡ç‰¹çš„ä¸¹éœåœ°è²Œå’Œæ¸…æ¾ˆè§åº•çš„é»„æ²³: ./gallery/2023-04-27/gallery.md
        - ç„¦è™‘çš„æ—¥å­é‡Œï¼Œä¸å¦¨æ”¾ä¸‹ä¸€åˆ‡ï¼Œå‡ºå»èµ°èµ°å§: ./gallery/2023-03-27/gallery.md
        - æ€»è¦å»è¶Ÿä¸Šæµ·å§ï¼Œå¹å¹é»„æµ¦æ±Ÿçš„æ™šé£: ./gallery/2023-03-01/gallery.md
        - ç”Ÿæ´»åŒ†å¿™ï¼Œåˆ«é”™è¿‡æ—¥è½å’Œå¤•é˜³: ./gallery/2023-02-28/gallery.md
        - è¿½èµ¶æ—¥è½å°±ç®—æˆ‘çŒ®ç»™è‡ªå·±çš„æµªæ¼«: ./gallery/2023-02-27/gallery.md
        - æ²¡æœ‰å¤§åŸå¸‚çš„ç¹åï¼Œå´æœ‰äººé—´æœ€çº¯å‡€çš„æœ´ç´ : ./gallery/2023-01-23/gallery.md
        - ä¸‡ç‰©çš†æœ‰è£‚ç—•ï¼Œé‚£æ˜¯é˜³å…‰ç…§è¿›æ¥çš„åœ°æ–¹: ./gallery/2023-01-10/gallery.md
        - ç©ºé»„çš„è·¯ç¯æ— åŠ›åœ°ç…§ç€æ²‰å¯‚çš„æ·±å··: ./gallery/2023-01-09/gallery.md
        - åŒ—äº¬åæµ·é™„è¿‘ï¼Œè¡—å¤´äººæ–‡çºªå®æ‘„å½±: ./gallery/2023-01-03/gallery.md
        - ä¸€å¹´å‰å»é€›å±•æ‹çš„é¹¦é¹‰ï¼Œé¢œè‰²å¤ªå¥½çœ‹äº†: ./gallery/2023-01-02/gallery.md
        - å¦‚ä»Šå·²æ˜¯ç¦»å¼€åŒ—äº¬çš„ç¬¬äºŒä¸ªå¹´å¤´äº†ï¼Œæ€€å¿µ: ./gallery/2023-01-01/gallery.md
      - 2022:
        - GR3ï½œå‚æ™šçš„è“è‰²æ˜¯æ²»æ„ˆï¼Œä¹Ÿæ˜¯æ¸©æŸ”: ./gallery/2022-12-18/gallery.md
        - GR3ï½œæ²¡æœ‰é”€å£°åŒ¿è¿¹ï¼Œæˆ‘åœ¨çƒ­çˆ±ç”Ÿæ´»: ./gallery/2022-12-03/gallery.md
        - GR3ï½œç­‰é²œèŠ±ç››å¼€ï¼Œäººé—´æ¸©æŸ”äº¦æµªæ¼«: ./gallery/2022-12-02/gallery.md
        - GR3ï½œä¹Œç¯·èˆ¹ç¼“ç¼“ä»æ°´é¢åˆ’è¿‡ï¼Œæº…èµ·é˜µé˜µæ¶Ÿæ¼ª: ./gallery/2022-12-01/gallery.md
        - GR3ï½œäººé—´æœæš®ï¼Œè½å¶æƒŠç§‹ï¼Œä½ æˆ‘çš†æ˜¯æ±Ÿå—å®¢: ./gallery/2022-11-25/gallery.md
        - GR3ï½œè¶é˜³å…‰æ­£å¥½ï¼Œè¶ç§‹æ„å°šåœ¨ï¼Œèµ¶å¿«å‡ºæ¥ç–¯å§: ./gallery/2022-11-24/gallery.md
        - GR3ï½œè¥¿æ¹–è¡—æ‹ï¼Œæœ‰å…‰ç†å…‰æ‰ä¼šç†ä½ : ./gallery/2022-11-22/gallery.md
        - GR3ï½œå‘é‡è€Œç”Ÿï¼Œæ€€å¿µä»¥å‰æ²¡æœ‰ç–«æƒ…çš„æ—¥å­: ./gallery/2022-11-14/gallery.md
        - è¿™ä¸ªå­£èŠ‚å¯å¤ªé€‚åˆæ¥è‰¯æ¸šæ•£å¿ƒæ‹ç…§äº†: ./gallery/2022-10-30/gallery.md
        - è®¸å¤šäººå’Œäº‹ä¸€æ—¦é”™è¿‡å°±ä¸å¯èƒ½å†é‡åˆ°äº†: ./gallery/2022-10-19/gallery.md
        - å¤§çƒ­å¤©çš„è°èƒ½æ‹’ç»ä¸€ä»½å†°å‡‰ç¾å‘³çš„é¾Ÿè‹“è†å‘¢: ./gallery/2022-10-05/gallery.md
        - è¿™æ‰æ˜¯æˆ‘è®°å¿†é‡Œå—æ–¹å°é•‡è¯¥æœ‰çš„æ ·å­ï¼: ./gallery/2022-10-04/gallery.md
        - å¦‚æœæœ‰ä¸å¼€å¿ƒçš„æ—¶å€™ï¼Œå»è‰¯æ¸šæ˜¯ä¸é”™çš„é€‰æ‹©: ./gallery/2022-10-01/gallery.md
        - ä»å¹¿å·å—ä¸‹ï¼Œåˆ°ç æµ·æƒ…ä¾£è·¯ï¼Œæ‰€åˆ°ä¹‹å¤„çš†ç¾æ™¯: ./gallery/2022-06-27/gallery.md
        - çœ‹åˆ°æ¸…æ™¨çƒˆç„°ä¼¼çš„äº‘éœï¼Œå°±çŸ¥é“è¿™ä¸€è¶Ÿæ²¡ç™½æ¥: ./gallery/2022-06-26/gallery.md
        - å¸Œæœ›ä½™ç”Ÿéƒ½èƒ½æµªè´¹åœ¨çƒ­çˆ±çš„äº‹æƒ…ä¸ŠğŸ“¸: ./gallery/2022-06-15/gallery.md
        - iPhoneï½œå·¥å‚é‡Œä¹Ÿèƒ½æ‹åˆ°ç»ç¾çš„ç…§ç‰‡: ./gallery/2022-05-29/gallery.md
        - iPhoneï½œéœ‡è€³å™ªéŸ³ä¸­æ¬è¿å¸ƒæ–™çš„çººç»‡å‚å·¥äºº: ./gallery/2022-05-15/gallery.md
        - è¿™ä¸€åˆ»ï¼Œé˜³å…‰å’Œå¾®é£çš„å®Œç¾ç›¸é‡: ./gallery/2022-04-12/gallery.md
        - æœ´æ ‘çš„éŸ³ä¹éœ€è¦åœ¨å¤œæ·±äººé™çš„æ—¶å€™å»å“å‘³: ./gallery/2022-04-11/gallery.md
        - ç­‰åˆ°ç–«æƒ…è¿‡å»ï¼Œå¸¦ç€Taï¼Œä¸€èµ·å»åˆ’èˆ¹å§: ./gallery/2022-04-08/gallery.md
        - å¦‚æœèƒ½å’Œä½ åˆ†äº«æ­¤åˆ»è¯¥å¤šå¥½: ./gallery/2022-04-07/gallery.md
        - é’æµ·ç„¦é»„è‰²å±±è„‰å’Œç›˜å±±å…¬è·¯â›°ï¸: ./gallery/2022-04-06/gallery.md
        - æ¯å‘¨å¿…è¾¾ï¼Œæ­å·ä¸´å¹³å¤§å‰§é™¢: ./gallery/2022-04-03/gallery.md
  - å…³äº: about.md

theme: 
  # logo: ./...
  # favicon: images/favicon.png
  name: material
  highlight: true
  font:
    code: Roboto Mono

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  palette:
    - scheme: default
      primary: black
      accent: black
    
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - content.code.copy
    
plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Eric54920
    
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/_ericphotograph

    - icon: fontawesome/solid/envelope
      link: mailto:realmaguodong@outlook.com

copyright: <div>Copyright &copy; 2024 <a href="http://theguodong.com">theguodong.com</a> All Right Reversed</div> <div><a href="https://beian.miit.gov.cn">æµ™ICPå¤‡2024102611å·-1</a></div>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html

extra_css:
  - assets/fancybox/fancybox.css
  - stylesheets/gallery.css

extra_javascript:
  - assets/fancybox/fancybox.umd.js
  - javascripts/gallery.js