site_name: Eric
site_url: http://theguodong.com

nav:
  - é¦–é¡µ: 
    - index.md
    - åç«¯:
      - Python:
        - ./articles/Python/index.md
        - Pythonè¯­è¨€ä»‹ç»: ./articles/Python/Pythonè¯­è¨€ä»‹ç».md
        - Pythonå˜é‡: ./articles/Python/Pythonå˜é‡.md
        - Pythonå¸¸é‡: ./articles/Python/Pythonå¸¸é‡.md
        - Pythonæ³¨é‡Š: ./articles/Python/Pythonæ³¨é‡Š.md
        - Pythonæ•°æ®ç±»å‹: ./articles/Python/Pythonæ•°æ®ç±»å‹.md
        - Pythonè¿ç®—ç¬¦: ./articles/Python/Pythonè¿ç®—ç¬¦.md
        - Pythonåˆ¤æ–­è¯­å¥: ./articles/Python/Pythonåˆ¤æ–­è¯­å¥.md
        - Pythonå¾ªç¯: ./articles/Python/Pythonå¾ªç¯.md
        - Pythonå­—ç¬¦ä¸²æ ¼å¼åŒ–: ./articles/Python/Pythonå­—ç¬¦ä¸²æ ¼å¼åŒ–.md
        - Pythonæ·±æµ…æ‹·è´: ./articles/Python/Pythonæ·±æµ…æ‹·è´.md
        - Pythonåºåˆ—åŒ–: ./articles/Python/Pythonåºåˆ—åŒ–.md
        - Pythonæ¨å¯¼å¼: ./articles/Python/Pythonæ¨å¯¼å¼.md
        - Pythonè¿­ä»£å™¨: ./articles/Python/Pythonè¿­ä»£å™¨.md
        - Pythonç”Ÿæˆå™¨: ./articles/Python/Pythonç”Ÿæˆå™¨.md
        - Pythonè£…é¥°å™¨: ./articles/Python/Pythonè£…é¥°å™¨.md
        - Pythonæ–‡ä»¶è¯»å†™: ./articles/Python/Pythonæ–‡ä»¶è¯»å†™.md
        - Pythonæ­£åˆ™è¡¨è¾¾å¼: ./articles/Python/Pythonæ­£åˆ™è¡¨è¾¾å¼.md
        - PythonåŒ¿åå‡½æ•°: ./articles/Python/PythonåŒ¿åå‡½æ•°.md
        - Pythonå‡½æ•°: ./articles/Python/Pythonå‡½æ•°.md
        - Pythonå‡½æ•°åçš„åº”ç”¨: ./articles/Python/Pythonå‡½æ•°åçš„åº”ç”¨.md
        - Pythoné€’å½’: ./articles/Python/Pythoné€’å½’.md
        - Pythoné—­åŒ…: ./articles/Python/Pythoné—­åŒ….md
        - Pythonåå°„: ./articles/Python/Pythonåå°„.md
        - Pythonå†…ç½®å‡½æ•°: ./articles/Python/Pythonå†…ç½®å‡½æ•°.md
        - Pythonå¼‚å¸¸å¤„ç†: ./articles/Python/Pythonå¼‚å¸¸å¤„ç†.md
        - Pythonæ¨¡å—å’ŒåŒ…: ./articles/Python/Pythonæ¨¡å—å’ŒåŒ….md
        - Pythonçš„functoolsæ¨¡å—: ./articles/Python/Pythonçš„functoolsæ¨¡å—.md
        - Pythonçš„osæ¨¡å—: ./articles/Python/Pythonçš„osæ¨¡å—.md
        - Pythonçš„sysæ¨¡å—: ./articles/Python/Pythonçš„sysæ¨¡å—.md
        - Pythonçš„timeæ¨¡å—: ./articles/Python/Pythonçš„timeæ¨¡å—.md
        - Pythonçš„datetimeæ¨¡å—: ./articles/Python/Pythonçš„datetimeæ¨¡å—.md
        - Pythonçš„randomæ¨¡å—: ./articles/Python/Pythonçš„randomæ¨¡å—.md
        - Pythonçš„jsonæ¨¡å—: ./articles/Python/Pythonçš„jsonæ¨¡å—.md
        - Pythonçš„hashlibæ¨¡å—: ./articles/Python/Pythonçš„hashlibæ¨¡å—.md
        - Pythonçš„loggingæ¨¡å—: ./articles/Python/Pythonçš„loggingæ¨¡å—.md
        - Pythonçš„collectionsæ¨¡å—: ./articles/Python/Pythonçš„collectionsæ¨¡å—.md
        - Pythonçš„stmplibæ¨¡å—: ./articles/Python/Pythonçš„stmplibæ¨¡å—.md
        - Pythonçš„socketæ¨¡å—: ./articles/Python/Pythonçš„socketæ¨¡å—.md
        - Pythoné¢å‘å¯¹è±¡: ./articles/Python/Pythoné¢å‘å¯¹è±¡.md
        - Pythonçš„å…ƒç±»: ./articles/Python/Pythonçš„å…ƒç±».md
        - Pythonç±»çš„ç»§æ‰¿: ./articles/Python/Pythonç±»çš„ç»§æ‰¿.md
        - Pythonçš„å°è£…: ./articles/Python/Pythonçš„å°è£….md
        - Pythonçš„å¤šæ€: ./articles/Python/Pythonçš„å¤šæ€.md
        - Pythonç±»çš„ç§æœ‰æˆå‘˜: ./articles/Python/Pythonç±»çš„ç§æœ‰æˆå‘˜.md
        - Pythonçš„ç‰¹æ®Šæ–¹æ³•: ./articles/Python/Pythonçš„ç‰¹æ®Šæ–¹æ³•.md
        - Pythonçš„æŠ½è±¡ç±»: ./articles/Python/Pythonçš„æŠ½è±¡ç±».md
        - Pythonä¿¡å·é‡: ./articles/Python/Pythonä¿¡å·é‡.md
        - Pythonè¿›ç¨‹: ./articles/Python/Pythonè¿›ç¨‹.md
        - Pythonçº¿ç¨‹: ./articles/Python/Pythonçº¿ç¨‹.md
        - Pythonçš„Event: ./articles/Python/Pythonçš„Event.md
        - Pythonå®šæ—¶å™¨: ./articles/Python/Pythonå®šæ—¶å™¨.md
        - Pythonçš„é”: ./articles/Python/Pythonçš„é”.md
        - Pythonçš„GIL: ./articles/Python/Pythonçš„GIL.md
        - Pythonçš„å¹¶å‘å’Œå¹¶è¡Œ: ./articles/Python/Pythonçš„å¹¶å‘å’Œå¹¶è¡Œ.md
        - Pythonåç¨‹: ./articles/Python/Pythonåç¨‹.md
        - Pythonçš„IOå¤šè·¯å¤ç”¨: ./articles/Python/Pythonçš„IOå¤šè·¯å¤ç”¨.md
        - Pythonå¼€å‘è§„èŒƒ: ./articles/Python/Pythonå¼€å‘è§„èŒƒ.md
        - Pythonä½¿ç”¨shutilå®ç°æ–‡ä»¶æ‹·è´: ./articles/Python/Pythonä½¿ç”¨shutilå®ç°æ–‡ä»¶æ‹·è´.md
        - Pythonä½¿ç”¨PILè¿›è¡Œå›¾ç‰‡å‹ç¼©: ./articles/Python/Pythonä½¿ç”¨PILè¿›è¡Œå›¾ç‰‡å‹ç¼©.md
        - Pythonè°ƒç”¨ChatGPT: ./articles/Python/Pythonè°ƒç”¨ChatGPT.md
      - Golang:
        - ./articles/Go/index.md
        - Goè¯­è¨€ä»‹ç»: ./articles/Go/Goè¯­è¨€ä»‹ç».md
    - å‰ç«¯:
      - Vue:
        - ./articles/Vue/index.md
    - æ•°æ®åº“:
      - MySQL:
        - ./articles/DataBase/MySQL/index.md
        - MySQLå­˜å‚¨å¼•æ“: ./articles/DataBase/MySQL/MySQLå­˜å‚¨å¼•æ“.md
        - MySQLå®Œæ•´æ€§çº¦æŸ: ./articles/DataBase/MySQL/MySQLå®Œæ•´æ€§çº¦æŸ.md
        - MySQLæ•°æ®ç±»å‹: ./articles/DataBase/MySQL/MySQLæ•°æ®ç±»å‹.md
        - MySQLæ­£åˆ™è¡¨è¾¾å¼: articles/DataBase/MySQL/MySQLæ­£åˆ™è¡¨è¾¾å¼.md
        - MySQLå†…ç½®å‡½æ•°: ./articles/DataBase/MySQL/MySQLå†…ç½®å‡½æ•°.md
        - MySQLè‡ªå®šä¹‰å‡½æ•°: ./articles/DataBase/MySQL/MySQLè‡ªå®šä¹‰å‡½æ•°.md
        - MySQLå­˜å‚¨è¿‡ç¨‹: ./articles/DataBase/MySQL/MySQLå­˜å‚¨è¿‡ç¨‹.md
        - MySQLæ•°æ®å¤‡ä»½ä¸æ¢å¤: ./articles/DataBase/MySQL/MySQLæ•°æ®å¤‡ä»½ä¸æ¢å¤.md
        - MySQLæƒé™ç®¡ç†: ./articles/DataBase/MySQL/MySQLæƒé™ç®¡ç†.md
        - MySQLæµç¨‹æ§åˆ¶: ./articles/DataBase/MySQL/MySQLæµç¨‹æ§åˆ¶.md
        - MySQLè§†å›¾: ./articles/DataBase/MySQL/MySQLè§†å›¾.md
        - MySQLç´¢å¼•: ./articles/DataBase/MySQL/MySQLç´¢å¼•.md
        - MySQLäº‹åŠ¡: ./articles/DataBase/MySQL/MySQLäº‹åŠ¡.md
        - MySQLè§¦å‘å™¨: ./articles/DataBase/MySQL/MySQLè§¦å‘å™¨.md
      - Redis:
        - ./articles/DataBase/Redis/index.md
        - RedisåŸºç¡€æ•°æ®ç±»å‹: ./articles/DataBase/Redis/RedisåŸºç¡€æ•°æ®ç±»å‹.md
        - Redisä¸»ä»å¤åˆ¶: ./articles/DataBase/Redis/Redisä¸»ä»å¤åˆ¶.md
        - Redisæ•°æ®æŒä¹…åŒ–: ./articles/DataBase/Redis/Redisæ•°æ®æŒä¹…åŒ–.md
        - Redisä¸é‡å¯æƒ…å†µä¸‹ï¼ŒRDBåˆ‡æ¢åˆ°AOF: ./articles/DataBase/Redis/Redisä¸é‡å¯æƒ…å†µä¸‹ï¼ŒRDBåˆ‡æ¢åˆ°AOF.md
        - ç¼“å­˜ç›¸å…³é—®é¢˜: ./articles/DataBase/Redis/ç¼“å­˜ç›¸å…³é—®é¢˜.md
    - ç‰ˆæœ¬æ§åˆ¶:
      - Git:
        - ./articles/Git/index.md
        - å¦‚ä½•ç»™å¼€æºé¡¹ç›®è´¡çŒ®ä»£ç : ./articles/Git/å¦‚ä½•ç»™å¼€æºé¡¹ç›®è´¡çŒ®ä»£ç .md
        - GitæŸ¥çœ‹å’Œé…ç½®ç¯å¢ƒä¿¡æ¯: ./articles/Git/GitæŸ¥çœ‹å’Œé…ç½®ç¯å¢ƒä¿¡æ¯.md
  - ç›¸å†Œ: 
    - gallery.md
    - æ—¶é—´çº¿:
      - 2024: 
        - GR3ï½œéº»æœ¨ä¸ä»çš„æ—¥å­é‡Œï¼Œè®°å½•å°±æ˜¯åæŠ—: ./gallery/2024-05-19/gallery.md
        - æ˜¥æ„æš–æš–ï¼Œå²æœˆç¼“ç¼“ï¼Œåœ¨æ„Ÿå—ï¼Œåœ¨è®°å½•ï¼Œåœ¨çæƒœ: ./gallery/2024-04-05/gallery.md
        - ä¸€èµ·å»å©ºæºå§ï¼Œçœ‹é‚£åº§å±±å´–ä¸Šè‚†æ„ç”Ÿé•¿çš„æ‘è½: ./gallery/2024-03-23/gallery.md
        - ä¹Œé•‡ï½œå¤©é’è‰²ç­‰çƒŸé›¨ï¼Œè€Œæˆ‘åœ¨ç­‰ä½ : ./gallery/2024-03-08/gallery.md
      - 2023:
        - æ€»è¦å¸¦ç€å–œæ¬¢çš„äººï¼Œå»çœ‹ä¸€çœ¼è”šè“çš„èµ›é‡Œæœ¨æ¹–: ./gallery/2023-06-09/gallery.md
        - ä½ ä¸åœ¨é‡åº†çš„æ—¥å­ï¼Œæˆ‘æ›¿ä½ å¹äº†å˜‰é™µæ±Ÿçš„æ™šé£: ./gallery/2023-06-08/gallery.md
        - åœ¨å……æ»¡é˜³å…‰çš„åœ°æ–¹ï¼Œå®‰é™çš„è¿æ¥æ¸©æš–çš„ä¸€å¤©: ./gallery/2023-05-07/gallery.md
        - é’æµ·è´µå¾·ï½œå¥‡ç‰¹çš„ä¸¹éœåœ°è²Œå’Œæ¸…æ¾ˆè§åº•çš„é»„æ²³: ./gallery/2023-04-27/gallery.md
        - ç„¦è™‘çš„æ—¥å­é‡Œï¼Œä¸å¦¨æ”¾ä¸‹ä¸€åˆ‡ï¼Œå‡ºå»èµ°èµ°å§: ./gallery/2023-03-27/gallery.md
        - æ€»è¦å»è¶Ÿä¸Šæµ·å§ï¼Œå¹å¹é»„æµ¦æ±Ÿçš„æ™šé£: ./gallery/2023-03-01/gallery.md
        - ç”Ÿæ´»åŒ†å¿™ï¼Œåˆ«é”™è¿‡æ—¥è½å’Œå¤•é˜³: ./gallery/2023-02-28/gallery.md
        - è¿½èµ¶æ—¥è½å°±ç®—æˆ‘çŒ®ç»™è‡ªå·±çš„æµªæ¼«: ./gallery/2023-02-27/gallery.md
        - æ²¡æœ‰å¤§åŸå¸‚çš„ç¹åï¼Œå´æœ‰äººé—´æœ€çº¯å‡€çš„æœ´ç´ : ./gallery/2023-01-23/gallery.md
        - ä¸‡ç‰©çš†æœ‰è£‚ç—•ï¼Œé‚£æ˜¯é˜³å…‰ç…§è¿›æ¥çš„åœ°æ–¹: ./gallery/2023-01-10/gallery.md
        - ç©ºé»„çš„è·¯ç¯æ— åŠ›åœ°ç…§ç€æ²‰å¯‚çš„æ·±å··: ./gallery/2023-01-09/gallery.md
        - åŒ—äº¬åæµ·é™„è¿‘ï¼Œè¡—å¤´äººæ–‡çºªå®æ‘„å½±: ./gallery/2023-01-03/gallery.md
        - ä¸€å¹´å‰å»é€›å±•æ‹çš„é¹¦é¹‰ï¼Œé¢œè‰²å¤ªå¥½çœ‹äº†: ./gallery/2023-01-02/gallery.md
        - å¦‚ä»Šå·²æ˜¯ç¦»å¼€åŒ—äº¬çš„ç¬¬äºŒä¸ªå¹´å¤´äº†ï¼Œæ€€å¿µ: ./gallery/2023-01-01/gallery.md
      - 2022:
        - GR3ï½œå‚æ™šçš„è“è‰²æ˜¯æ²»æ„ˆï¼Œä¹Ÿæ˜¯æ¸©æŸ”: ./gallery/2022-12-18/gallery.md
        - GR3ï½œæ²¡æœ‰é”€å£°åŒ¿è¿¹ï¼Œæˆ‘åœ¨çƒ­çˆ±ç”Ÿæ´»: ./gallery/2022-12-03/gallery.md
        - GR3ï½œç­‰é²œèŠ±ç››å¼€ï¼Œäººé—´æ¸©æŸ”äº¦æµªæ¼«: ./gallery/2022-12-02/gallery.md
        - GR3ï½œä¹Œç¯·èˆ¹ç¼“ç¼“ä»æ°´é¢åˆ’è¿‡ï¼Œæº…èµ·é˜µé˜µæ¶Ÿæ¼ª: ./gallery/2022-12-01/gallery.md
        - GR3ï½œäººé—´æœæš®ï¼Œè½å¶æƒŠç§‹ï¼Œä½ æˆ‘çš†æ˜¯æ±Ÿå—å®¢: ./gallery/2022-11-25/gallery.md
        - GR3ï½œè¶é˜³å…‰æ­£å¥½ï¼Œè¶ç§‹æ„å°šåœ¨ï¼Œèµ¶å¿«å‡ºæ¥ç–¯å§: ./gallery/2022-11-24/gallery.md
        - GR3ï½œè¥¿æ¹–è¡—æ‹ï¼Œæœ‰å…‰ç†å…‰æ‰ä¼šç†ä½ : ./gallery/2022-11-22/gallery.md
        - GR3ï½œå‘é‡è€Œç”Ÿï¼Œæ€€å¿µä»¥å‰æ²¡æœ‰ç–«æƒ…çš„æ—¥å­: ./gallery/2022-11-14/gallery.md
        - è¿™ä¸ªå­£èŠ‚å¯å¤ªé€‚åˆæ¥è‰¯æ¸šæ•£å¿ƒæ‹ç…§äº†: ./gallery/2022-10-30/gallery.md
        - è®¸å¤šäººå’Œäº‹ä¸€æ—¦é”™è¿‡å°±ä¸å¯èƒ½å†é‡åˆ°äº†: ./gallery/2022-10-19/gallery.md
        - å¤§çƒ­å¤©çš„è°èƒ½æ‹’ç»ä¸€ä»½å†°å‡‰ç¾å‘³çš„é¾Ÿè‹“è†å‘¢: ./gallery/2022-10-05/gallery.md
        - è¿™æ‰æ˜¯æˆ‘è®°å¿†é‡Œå—æ–¹å°é•‡è¯¥æœ‰çš„æ ·å­ï¼: ./gallery/2022-10-04/gallery.md
        - å¦‚æœæœ‰ä¸å¼€å¿ƒçš„æ—¶å€™ï¼Œå»è‰¯æ¸šæ˜¯ä¸é”™çš„é€‰æ‹©: ./gallery/2022-10-01/gallery.md
        - ä»å¹¿å·å—ä¸‹ï¼Œåˆ°ç æµ·æƒ…ä¾£è·¯ï¼Œæ‰€åˆ°ä¹‹å¤„çš†ç¾æ™¯: ./gallery/2022-06-27/gallery.md
        - çœ‹åˆ°æ¸…æ™¨çƒˆç„°ä¼¼çš„äº‘éœï¼Œå°±çŸ¥é“è¿™ä¸€è¶Ÿæ²¡ç™½æ¥: ./gallery/2022-06-26/gallery.md
        - å¸Œæœ›ä½™ç”Ÿéƒ½èƒ½æµªè´¹åœ¨çƒ­çˆ±çš„äº‹æƒ…ä¸ŠğŸ“¸: ./gallery/2022-06-15/gallery.md
        - iPhoneï½œå·¥å‚é‡Œä¹Ÿèƒ½æ‹åˆ°ç»ç¾çš„ç…§ç‰‡: ./gallery/2022-05-29/gallery.md
        - iPhoneï½œéœ‡è€³å™ªéŸ³ä¸­æ¬è¿å¸ƒæ–™çš„çººç»‡å‚å·¥äºº: ./gallery/2022-05-15/gallery.md
        - è¿™ä¸€åˆ»ï¼Œé˜³å…‰å’Œå¾®é£çš„å®Œç¾ç›¸é‡: ./gallery/2022-04-12/gallery.md
        - æœ´æ ‘çš„éŸ³ä¹éœ€è¦åœ¨å¤œæ·±äººé™çš„æ—¶å€™å»å“å‘³: ./gallery/2022-04-11/gallery.md
        - ç­‰åˆ°ç–«æƒ…è¿‡å»ï¼Œå¸¦ç€Taï¼Œä¸€èµ·å»åˆ’èˆ¹å§: ./gallery/2022-04-08/gallery.md
        - å¦‚æœèƒ½å’Œä½ åˆ†äº«æ­¤åˆ»è¯¥å¤šå¥½: ./gallery/2022-04-07/gallery.md
        - é’æµ·ç„¦é»„è‰²å±±è„‰å’Œç›˜å±±å…¬è·¯â›°ï¸: ./gallery/2022-04-06/gallery.md
        - æ¯å‘¨å¿…è¾¾ï¼Œæ­å·ä¸´å¹³å¤§å‰§é™¢: ./gallery/2022-04-03/gallery.md
  - å…³äº: about.md

theme: 
  logo: ./assets/img/myLOGO.png
  favicon: ./assets/img/icon.png
  name: material
  language: zh
  font:
    code: Roboto Mono

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  palette:
    - scheme: default
      primary: black
      accent: black
    
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - content.code.copy
    
plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Eric54920
    
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/_ericphotograph

    - icon: fontawesome/solid/envelope
      link: mailto:realmaguodong@outlook.com

copyright: <div>Copyright &copy; 2024 <a href="http://theguodong.com">theguodong.com</a> All Right Reversed</div> <div><a href="https://beian.miit.gov.cn">æµ™ICPå¤‡2024102611å·-1</a></div>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

extra_css:
  - assets/fancybox/fancybox.css
  - stylesheets/gallery.css

extra_javascript:
  - assets/fancybox/fancybox.umd.js
  - javascripts/gallery.js